export default [
  {
    employer_name: "Sanofi Global (English)",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReu9h4fboxyPxVwYMcnBF_dO5X6HfPWGhRSVQK&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "Sanofi Global (English)",
    job_id: "UHE-nWdKAbAAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "HEOR Director- Rare Disease",
    job_apply_link:
      "https://en.jobs.sanofi.com/job/cambridge/heor-director-rare-disease/20873/51508082496",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.7154,
    job_description:
      "HEOR Director Job Description (Director/Senior Director)\n\nPurpose of Role\n\nTo support rare disease portfolio to plan and generate robust evidence to maximize the value propositions from both a global and US perspectives working within the market access team.\n\nMajor Activities / Key Responsibilities\n\nHealth Economics strategy, evidence generation and reimbursement support\n\nOversee and guide development of quality research projects, economic models, trial design recommendations and other activities in support of programs/products . The incumbent interfaces with Clinical, Medical Affairs and business partners including Marketing, External Affairs and Market Access. He/she is accountable for the overseeing direct report at director level on product launches and post launch evidence generation activities. The incumbent will also lead planning, design, implementation and completion of innovative evidence based research programs that are consistent with program/product strategies. The research programs developed will provide appropriate evidence and/or tools to be used for internal decision making and for external audiences at product launch and over product life cycle.\n• Develops strategies and provides new ideas and concepts on how to move the program, product or therapeutic franchise forward\n• Manage the HEVA evidence generation strategy\n• Manage team budgets and execution of ongoing studies according to budget and timeline expectations\n• Identify new HEVA evidence generation opportunities to maximize lifecycle management\n• Assist countries in developing or adapting health economic models and other materials for reimbursement, payer objection handling and other purposes\n• Develop and maintain effective relationships with key internal stakeholders including North American Medical Affairs, European Medical Affairs, Sanofi Emerging Market regional teams, and Established Products.\n• Sets strategic evidence generation priorities and direction for assigned responsibilities and is able to incorporate this into appropriate planning documents\n• Takes a leadership role in the development of relationships and continued advocacy with external advisors in appropriate therapeutic areas\n• Develops collaborative research relationships that provide data of value to decision makers. Leverages interactions to identify strategies that will improve the impact of research and build advocates for data\n• Interacts with senior level management providing high level strategies and long term vision of assigned work\n• Implementation of evidence generation tactics consistent with HEVA strategic goals including designing, budgeting, contracting, tracking, reporting, and publication plans\n• Provides input to clinical and medical teams regarding opportunities to execute HEVA strategies within their planned research activities by identifying the appropriate evidence to collect and report\n• Serves as a resource to commercial organization in terms of pricing, positioning and reimbursement of products based on economic evaluations\n\nAbout You\n• All incumbents are expected to demonstrate effective communication, organizational and interpersonal skills to be able to work effectively as part of a multidisciplinary team.\n• The incumbent is expected to work independently, but in concert with the direction provided by their management, in accordance with defined functional policies and precedents, budgetary guidelines, company values, ethics and applicable law.\n• MSc or PhD or equivalent in health economics, epidemiology, statistics, biostatistics or related discipline\n• Prior relevant experience working, at least 8 years, as a pharmaco-economist, HEOR and/or Market Access in consultancy, CRO or pharmaceutical/biotech\n• Strong time-management and organizational skills\n• Attitude to work well as a member of team and to build and manage relationships in a multi-cultural environment\n\nSanofi Inc. and its U.S. affiliates are Equal Opportunity and Affirmative Action employers committed to a culturally diverse workforce. All qualified applicants will receive consideration for employment without regard to race; color; creed; religion; national origin; age; ancestry; nationality; marital, domestic partnership or civil union status; sex, gender, gender identity or expression; affectional or sexual orientation; disability; veteran or military status or liability for military status; domestic violence victim status; atypical cellular or blood trait; genetic information (including the refusal to submit to genetic testing) or any other characteristic protected by law.\n\n#GD-SG\n#LI-GZ\n\nAt Sanofi diversity and inclusion is foundational to how we operate and embedded in our Core Values. We recognize to truly tap into the richness diversity brings we must lead with inclusion and have a workplace where those differences can thrive and be leveraged to empower the lives of our colleagues, patients and customers. We respect and celebrate the diversity of our people, their backgrounds and experiences and provide equal opportunity for all.",
    job_is_remote: false,
    job_posted_at_timestamp: 1689120000,
    job_posted_at_datetime_utc: "2023-07-12T00:00:00.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: ["health_insurance"],
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=jobs&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=jobs&htidocid=UHE-nWdKAbAAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "All incumbents are expected to demonstrate effective communication, organizational and interpersonal skills to be able to work effectively as part of a multidisciplinary team",
        "The incumbent is expected to work independently, but in concert with the direction provided by their management, in accordance with defined functional policies and precedents, budgetary guidelines, company values, ethics and applicable law",
        "MSc or PhD or equivalent in health economics, epidemiology, statistics, biostatistics or related discipline",
        "Prior relevant experience working, at least 8 years, as a pharmaco-economist, HEOR and/or Market Access in consultancy, CRO or pharmaceutical/biotech",
        "Strong time-management and organizational skills",
        "Attitude to work well as a member of team and to build and manage relationships in a multi-cultural environment",
      ],
      Responsibilities: [
        "To support rare disease portfolio to plan and generate robust evidence to maximize the value propositions from both a global and US perspectives working within the market access team",
        "Health Economics strategy, evidence generation and reimbursement support",
        "Oversee and guide development of quality research projects, economic models, trial design recommendations and other activities in support of programs/products ",
        "The incumbent interfaces with Clinical, Medical Affairs and business partners including Marketing, External Affairs and Market Access",
        "He/she is accountable for the overseeing direct report at director level on product launches and post launch evidence generation activities",
        "The incumbent will also lead planning, design, implementation and completion of innovative evidence based research programs that are consistent with program/product strategies",
        "The research programs developed will provide appropriate evidence and/or tools to be used for internal decision making and for external audiences at product launch and over product life cycle",
        "Develops strategies and provides new ideas and concepts on how to move the program, product or therapeutic franchise forward",
        "Manage team budgets and execution of ongoing studies according to budget and timeline expectations",
        "Identify new HEVA evidence generation opportunities to maximize lifecycle management",
        "Assist countries in developing or adapting health economic models and other materials for reimbursement, payer objection handling and other purposes",
        "Develop and maintain effective relationships with key internal stakeholders including North American Medical Affairs, European Medical Affairs, Sanofi Emerging Market regional teams, and Established Products",
        "Sets strategic evidence generation priorities and direction for assigned responsibilities and is able to incorporate this into appropriate planning documents",
        "Takes a leadership role in the development of relationships and continued advocacy with external advisors in appropriate therapeutic areas",
        "Develops collaborative research relationships that provide data of value to decision makers",
        "Leverages interactions to identify strategies that will improve the impact of research and build advocates for data",
        "Interacts with senior level management providing high level strategies and long term vision of assigned work",
        "Implementation of evidence generation tactics consistent with HEVA strategic goals including designing, budgeting, contracting, tracking, reporting, and publication plans",
        "Provides input to clinical and medical teams regarding opportunities to execute HEVA strategies within their planned research activities by identifying the appropriate evidence to collect and report",
        "Serves as a resource to commercial organization in terms of pricing, positioning and reimbursement of products based on economic evaluations",
      ],
    },
    job_job_title: "Director",
    job_posting_language: "en",
    job_onet_soc: "19301100",
    job_onet_job_zone: "5",
  },
  {
    employer_name: "KJ Info LLC",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTvPIJOTNmLBtrFmCoDyJG7vUAHf--hqv8pewU&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "dUqfpQ2XLCwAAAAAAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "SAP Hybris / Commerce Cloud Consultant",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/sap-hybris-commerce-cloud-consultant-at-kj-info-llc-3657086311",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5932,
    job_description:
      "We are looking for Multiple SAP Hybris / Commerce Cloud Consultants towards multiple open positions with our client to work remotely on any of the below roles:\n\n1) Frontend Angular Developer\n\n2) Transition Manager\n\n3) Technical Project Manager\n\n4) SEO Expert\n\n5) Functional Lead Consultant\n\n6) Hybris Lead Developer\n\nIf you have suitable candidates, do share the updated resumes on email: dee@kjinfo.biz or contact Deeksha: 551-888-0066",
    job_is_remote: true,
    job_posted_at_timestamp: 1689121089,
    job_posted_at_datetime_utc: "2023-07-12T00:18:09.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=jobs&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=jobs&htidocid=dUqfpQ2XLCwAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-01-08T00:18:02.000Z",
    job_offer_expiration_timestamp: 1704673082,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: false,
      experience_preferred: false,
    },
    job_required_skills: [
      "SAP Marketing Cloud",
      "Cloud Computing",
      "Commerce",
      "Statutory Accounting Principles (SAP)",
      "Project Management",
      "Service Work",
    ],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {},
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15112100",
    job_onet_job_zone: "4",
  },
  {
    employer_name: "Kansas Behavior Supports",
    employer_logo: null,
    employer_website: null,
    employer_company_type: null,
    job_publisher: "WJHL Jobs",
    job_id: "Bl8A1-pagCUAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Autism Paraprofessional Position",
    job_apply_link:
      "https://jobs.wjhl.com/jobs/autism-paraprofessional-position-yates-center-kansas/1062638712-2/",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5562,
    job_description:
      "Are you looking for a career that truly makes a difference in the world? Do you want to be part of our mission to help children with Autism reach their full potential and live happy, fulfilling lives?\n\nConsider a well-paying job in the Applied Behavior Analysis (ABA) field, where you can make real change for children and their families.\n\nUnder the supervision of a BCBA, you'll work directly with our clients, using evidence-based interventions to help them overcome challenging behaviors and achieve their goals.\n\nBy joining the ABA field you'll be part of a community of dedicated professionals who are passionate about improving the lives of others.\nWe offer free comprehensive training with the option of obtaining a nationally recognized certification.\nYou will be offered flexibility and autonomy over your schedule so you can balance your work and personal life!\nYou will be compensated well with hourly rates ranging from $14-$18 an hour!\n\nApply today to begin your career in ABA and make the world a better place!\n\nLearn more by visiting our site:\n\nKey words: RBT, RBT, RBT, RBT, RBT, Behavior Technician, Behavior Technician, Behavior Technician, Behavior Technician, Behavior Technician, Registered Behavior Technician, Registered Behavior Technician, Registered Behavior Technician, Registered Behavior Technician, Mental Health Technician, Behavioral Health, Behavioral Health, Behavioral Health, Behavioral Health, ABA, ABA, ABA, ABA, Autism, Autism, Autism, Autism, Psychology, Psychology, Psychology, Psychology\n\nowyhwSA8Ee",
    job_is_remote: false,
    job_posted_at_timestamp: 1689155290,
    job_posted_at_datetime_utc: "2023-07-12T09:48:10.000Z",
    job_city: "Yates Center",
    job_state: "KS",
    job_country: "US",
    job_latitude: 37.881145,
    job_longitude: -95.733315,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=jobs&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=jobs&htidocid=Bl8A1-pagCUAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: false,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: true,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 14,
    job_max_salary: 18,
    job_salary_currency: "USD",
    job_salary_period: "HOUR",
    job_highlights: {
      Responsibilities: [
        "Under the supervision of a BCBA, you'll work directly with our clients, using evidence-based interventions to help them overcome challenging behaviors and achieve their goals",
      ],
      Benefits: [
        "You will be offered flexibility and autonomy over your schedule so you can balance your work and personal life!",
        "You will be compensated well with hourly rates ranging from $14-$18 an hour!",
      ],
    },
    job_job_title: "Paraprofessional",
    job_posting_language: "en",
    job_onet_soc: "25904100",
    job_onet_job_zone: "3",
  },
  {
    employer_name: "Upwork",
    employer_logo: "https://image.status.io/z6aeO6kAGsAG.png",
    employer_website: "http://www.elance.com",
    employer_company_type: "Computer Services",
    job_publisher: "Upwork",
    job_id: "SyL4i7DZQZUAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Financial Analyst and Programmer - Contract to Hire",
    job_apply_link:
      "https://www.upwork.com/freelance-jobs/apply/Financial-Analyst-and-Programmer_~0130a0acfd35476338/",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.681,
    job_description:
      "Looking for a Financial Analyst and Programmer for LBO Modeling with a private company. The Dashboard is in React. Python API experience would be a plus as well.\n\nThe current LBO model I am using only has the ability to make one very special loan. My dream is to be able to add any debt or equity to the financing sheet. So if I wanted to add a 5-year loan with PIK interest and a cash flow sweep of 100%, any additional cash flows out would update my rates of return.\n\nAfter new debts, preferred stock, and equity, here are the new IRR and Cash on Cash benchmarks.\n\nPrior experience as a consultant would be an advantage because as I have more clients, the more we need to use the model and software we are creating. Therefore, this engagement could turn into full-time consulting at a high rate of compensation.\n\nI’ll set up a Zoom call and give you more details.\n\nThanks\n\nJosh",
    job_is_remote: true,
    job_posted_at_timestamp: 1689121049,
    job_posted_at_datetime_utc: "2023-07-12T00:17:29.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=jobs&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=jobs&htidocid=SyL4i7DZQZUAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: [
      "Valuation",
      "Company Valuation",
      "Financial Projection",
      "Financial Modeling",
      "Python",
      "Leveraged",
      "React",
    ],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Benefits: [
        "Therefore, this engagement could turn into full-time consulting at a high rate of compensation",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113100",
    job_onet_job_zone: "4",
    job_naics_code: "541511",
    job_naics_name: "Custom Computer Programming Services",
  },
  {
    employer_name: "Geisinger",
    employer_logo:
      "https://www.geisinger.org/-/media/OneGeisinger/Images/Logos/geisingerlogo.png?h=100&la=en&w=275&hash=BBE45E3CBE29A43C524B45F49BAED87C5C5AD043",
    employer_website: "http://www.geisinger.org",
    employer_company_type: "Health Care",
    job_publisher: "Guardian Jobs",
    job_id: "aCsN2nkkMqYAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Registered Nurse (RN)",
    job_apply_link:
      "https://jobs.theguardian.com/job/8579098/registered-nurse-rn-/?LinkSource=SEOLandingPageListing",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.7148,
    job_description:
      "Job Title: Inpatient RN- Advanced Acute Care Trauma - Up to $26K Hiring Incentive!\nLocation: Danville, Pennsylvania\nJob Category: Inpatient RN - Registered Nurse, Nursing and Nursing Support\nSchedule: Nights\nWork Type: Full time\nDepartment: GMC Medical-Surgical/Telemetry Nursing Division\nDate Posted: 10/03/2022\nJob ID: R-38660\nJob Summary Are you a RN looking to join our Geisinger Nursing Institute? Through professional growth, quality improvement and interdisciplinary collaboration, we've built an innovative culture that allows our nurses to grow their skillset, develop their practice and leverage their years of experience to build a rewarding, lasting career with impact.\n\nAssesses plans, organizes, performs, and evaluates nursing activities to meet the needs of the patient. Promotes adaptive responses of patient and family to achieve the highest level of patient care, promote safety, and maximize patient satisfaction. Exhibits compassionate care during patient-nurse interactions. Coordinates patient care and interaction of staff. Meets the qualifications to provide care for patients in their assigned nursing unit. Responsible for ensuring the very best patient and family experience by optimizing all interactions.\nJob Duties\n• Completes assessments as established by scope of practice and unit standards.\n• Addresses physical, psychological, social, cultural, and spiritual needs of patient and family throughout the continuum of care.\n• Formulates, coordinates, and provides plan of care as established in unit standards including, patient and family education, family needs and discharge planning throughout hospitalization with members of the interdisciplinary team.\n• Provides direct patient care including, treatments, medications, and diagnostic studies according to policy and procedure.\n• Evaluates effectiveness of nursing interventions and revises plan of care based upon patient response to interventions.\n• Initiates collaboration with physicians, ancillary personnel, and other interdisciplinary team members and acts to proactively resolve and facilitate patient needs.\n• Problem solves, troubleshoots and takes corrective measures in the care and handling of equipment.\n• Participates in unit-based decision-making regarding the utilization of evidence- based practice.\n• Actively participates as a team member working toward team goals of the unit and organization and is accountable for unit and system specific metrics.\n• Actively participates in patient quality and safety education programs and other activities designed to improve departmental and organizational quality and safety.\n\nWork is typically performed in a clinical environment. Accountable for satisfying all job specific obligations and complying with all organization policies and procedures. The specific statements in this profile are not intended to be all-inclusive. They represent typical elements considered necessary to successfully perform the job. Additional competencies and skills outlined in any department-specific orientation will be considered essential to the performance of the job related to that position.\n\nPosition Details\nWe're proud to offer:\n• $35.25 minimum hiring rate with increased rates for experienced individuals\n• Up to $7 shift differentials for evening, nights and weekend shifts\n• Up to $26,000 hiring incentive for eligible candidates\n• Comprehensive benefits package, including health insurance that starts day one of employment\n• Relocation assistance for eligible candidates\n• MyHealth Rewards wellness program to enhance personal health and reduce health plan premiums for qualified individuals\n• Up to $5000 in tuition reimbursement per year\n• Robust PTO plan in addition to six paid holidays and 32 hours of personal time per year\n• Competitive 401k plan that includes automatic Geisinger contributions starting day one of employment\n• Paid parental leave and military leave\n• Fertility and adoption support\n• The ability to work under a Temporary Practice Permit until you take NCLEX\n• Shared governance structure that empowers our nurses\n• Professional opportunities for growth and advancement\n• Support and mentorship from a full range of dedicated nursing leaders\n• Community involvement through our Employee Resource Groups\n• Employee referral incentive program\n\nJoin the Geisinger Family! Apply now! To learn more about Geisinger opportunities, please contact Katy Baralt, Nurse Recruiter, at ksbaralt@geisinger.edu.\n\nUnit Location: BP\n\nEducation Graduate from Specialty Training Program-Nursing (Required)\nCertification(s) and License(s) Licensed Registered Nurse (Pennsylvania) - RN_State of Pennsylvania; Basic Life Support Certification - Default Issuing Body\nOur Purpose & Values OUR PURPOSE & VALUES: Everything we do is about caring for our patients, our members, our students, our Geisinger family and our communities. KINDNESS: We strive to treat everyone as we would hope to be treated ourselves. EXCELLENCE: We treasure colleagues who humbly strive for excellence. LEARNING: We share our knowledge with the best and brightest to better prepare the caregivers for tomorrow. INNOVATION: We constantly seek new and better ways to care for our patients, our members, our community, and the nation. SAFETY: We provide a safe environment for our patients and members and the Geisinger family We offer healthcare benefits for full time and part time positions from day one, including vision, dental and domestic partners. Perhaps just as important, from senior management on down, we encourage an atmosphere of collaboration, cooperation and collegiality. We know that a diverse workforce with unique experiences and backgrounds makes our team stronger. Our patients, members and community come from a wide variety of backgrounds, and it takes a diverse workforce to make better health easier for all. We are proud to be an affirmative action, equal opportunity employer and all qualified applicants will receive consideration for employment regardless to race, color, religion, sex, sexual orientation, gender identity, national origin, disability or status as a protected veteran.",
    job_is_remote: false,
    job_posted_at_timestamp: 1689116400,
    job_posted_at_datetime_utc: "2023-07-11T23:00:00.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: [
      "retirement_savings",
      "dental_coverage",
      "paid_time_off",
      "health_insurance",
    ],
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=jobs&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=jobs&htidocid=aCsN2nkkMqYAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-07-16T23:00:00.000Z",
    job_offer_expiration_timestamp: 1689548400,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: true,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "The ability to work under a Temporary Practice Permit until you take NCLEX",
        "Education Graduate from Specialty Training Program-Nursing (Required)",
        "Certification(s) and License(s) Licensed Registered Nurse (Pennsylvania) - RN_State of Pennsylvania; Basic Life Support Certification - Default Issuing Body",
      ],
      Responsibilities: [
        "Assesses plans, organizes, performs, and evaluates nursing activities to meet the needs of the patient",
        "Promotes adaptive responses of patient and family to achieve the highest level of patient care, promote safety, and maximize patient satisfaction",
        "Exhibits compassionate care during patient-nurse interactions",
        "Coordinates patient care and interaction of staff",
        "Meets the qualifications to provide care for patients in their assigned nursing unit",
        "Responsible for ensuring the very best patient and family experience by optimizing all interactions",
        "Completes assessments as established by scope of practice and unit standards",
        "Addresses physical, psychological, social, cultural, and spiritual needs of patient and family throughout the continuum of care",
        "Formulates, coordinates, and provides plan of care as established in unit standards including, patient and family education, family needs and discharge planning throughout hospitalization with members of the interdisciplinary team",
        "Provides direct patient care including, treatments, medications, and diagnostic studies according to policy and procedure",
        "Evaluates effectiveness of nursing interventions and revises plan of care based upon patient response to interventions",
        "Initiates collaboration with physicians, ancillary personnel, and other interdisciplinary team members and acts to proactively resolve and facilitate patient needs",
        "Problem solves, troubleshoots and takes corrective measures in the care and handling of equipment",
        "Participates in unit-based decision-making regarding the utilization of evidence- based practice",
        "Actively participates as a team member working toward team goals of the unit and organization and is accountable for unit and system specific metrics",
        "Actively participates in patient quality and safety education programs and other activities designed to improve departmental and organizational quality and safety",
        "Work is typically performed in a clinical environment",
        "Accountable for satisfying all job specific obligations and complying with all organization policies and procedures",
      ],
      Benefits: [
        "$35.25 minimum hiring rate with increased rates for experienced individuals",
        "Up to $7 shift differentials for evening, nights and weekend shifts",
        "Up to $26,000 hiring incentive for eligible candidates",
        "Comprehensive benefits package, including health insurance that starts day one of employment",
        "Relocation assistance for eligible candidates",
        "MyHealth Rewards wellness program to enhance personal health and reduce health plan premiums for qualified individuals",
        "Up to $5000 in tuition reimbursement per year",
        "Robust PTO plan in addition to six paid holidays and 32 hours of personal time per year",
        "Competitive 401k plan that includes automatic Geisinger contributions starting day one of employment",
        "Paid parental leave and military leave",
        "Fertility and adoption support",
        "Shared governance structure that empowers our nurses",
        "Professional opportunities for growth and advancement",
        "Support and mentorship from a full range of dedicated nursing leaders",
        "Community involvement through our Employee Resource Groups",
        "Employee referral incentive program",
      ],
    },
    job_job_title: "Registered nurse",
    job_posting_language: "en",
    job_onet_soc: "29114100",
    job_onet_job_zone: "3",
    job_naics_code: "622110",
    job_naics_name: "General Medical and Surgical Hospitals",
  },
  {
    employer_name: "EVONA",
    employer_logo: null,
    employer_website: null,
    employer_company_type: null,
    job_publisher: "Indeed",
    job_id: "FYB-XE2aRNMAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Project Manager",
    job_apply_link: "https://www.indeed.com/viewjob?jk=38f27d254d41770d",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6171,
    job_description:
      "Our client, a leading New Space company, is seeking a highly skilled Project Manager to join their dynamic team. Backed by a decade of experience and a team of talented engineers from renowned industry leaders, they are at the forefront of Defense, Civil, and Commercial programs, making significant contributions to the aerospace industry.??\n\nAs the Project Manager, you will be responsible for planning, developing, and executing projects related to the delivery of in-space propulsion systems. You will lead multi-disciplinary teams and oversee the delivery of flight hardware for various missions; ensuring project scope, cost, and schedule are meticulously managed to achieve exceptional performance. You'll be involved with coordinating design, procurement, testing, qualification, and production across multiple projects.\n\nRequirements:\n• Bachelor's Degree in Engineering, Science or a related technical field.\n• A minimum of 10 years of relevant industry experience.\n• Proven leadership experience.\n• Demonstrated track record of successfully managing small to large-scale projects.\n• Excellent verbal and written communication skills, including technical documentation.\n• Background in engineering, production or manufacturing environments.\n• Working knowledge of Project Controls, including cost and schedule management systems.\n• Experience managing DOD contracts.\n• Must be a US Citizen, eligibility for security clearance is required.\n\nThis is a great opportunity to join an innovative team and contribute to the advancement of in-space propulsion systems.",
    job_is_remote: false,
    job_posted_at_timestamp: 1689097124,
    job_posted_at_datetime_utc: "2023-07-11T17:38:44.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=jobs&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=jobs&htidocid=FYB-XE2aRNMAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 120,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Bachelor's Degree in Engineering, Science or a related technical field",
        "A minimum of 10 years of relevant industry experience",
        "Proven leadership experience",
        "Demonstrated track record of successfully managing small to large-scale projects",
        "Excellent verbal and written communication skills, including technical documentation",
        "Background in engineering, production or manufacturing environments",
        "Working knowledge of Project Controls, including cost and schedule management systems",
        "Experience managing DOD contracts",
        "Must be a US Citizen, eligibility for security clearance is required",
        "This is a great opportunity to join an innovative team and contribute to the advancement of in-space propulsion systems",
      ],
      Responsibilities: [
        "As the Project Manager, you will be responsible for planning, developing, and executing projects related to the delivery of in-space propulsion systems",
        "You will lead multi-disciplinary teams and oversee the delivery of flight hardware for various missions; ensuring project scope, cost, and schedule are meticulously managed to achieve exceptional performance",
        "You'll be involved with coordinating design, procurement, testing, qualification, and production across multiple projects",
      ],
    },
    job_job_title: "Project manager",
    job_posting_language: "en",
    job_onet_soc: "13108200",
    job_onet_job_zone: null,
  },
  {
    employer_name: "SPECTRAFORCE",
    employer_logo:
      "https://spectraforce.com/wp-content/uploads/2020/03/email-footer-logo2b.gif",
    employer_website: "http://www.spectraforce.com",
    employer_company_type: "Computer Services",
    job_publisher: "LinkedIn",
    job_id: "J-owA0CXF9QAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Toxicologist",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/toxicologist-at-spectraforce-3661111029",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5406,
    job_description:
      "Job Title: Computational Chemistry/Toxicology Scientist\n\nJob Location: Zionsville, IN 46077\n\nJob Duration: 12 Months\n\nThe client has an exciting and challenging opportunity in the Predictive Safety Center (PSC) within Regulatory Science for a Computational Chemistry/Toxicology Scientist. The individual will partner with a multidisciplinary team to design, develop, and implement machine learning models to predict safety profiles of chemicals to support the discovery, development and registration of novel crop protection products.\n\nResponsibilities:\n\n• Develop and apply chemistry structure-based predictive models for assessing safety profiles of early stage discovery molecules\n\n• Work collaboratively with internal and external cross-functional multidisciplinary teams, collaborators, and consultants to implement in silico models to meet business needs\n\n• Serve as a subject matter expert on in silico modelling for the team and other partners in R&D sub-functions\n\n• Present the development and application of cheminformatics approaches and novel ML/DL models internally and externally including scientific conferences\n\n• Keep abreast of the latest scientific development in the areas of machine learning, cheminformatics, and related fields and identify technologies to be applied internally\n\n• Provide mentorship and coaching to team members on in silico modelling and applications. Promote sharing of information and a team-oriented spirit of collaboration.\n\n• Analyze complex datasets using machine learning approaches and interpret results to improve data-driven decision-making processes.\n\nQualifications:\n\n• Ph.D. degree in Cheminformatics, Computational Chemistry, Computer Science, Statistics, Bioinformatics, Toxicology, or a related field\n\n• 3+ years of experience in developing machine learning models and applying cheminformatics and AI for structure-based drug design, toxicology assessment, and metabolism prediction\n\n• Strong technical background in machine learning, deep learning, and statistical modeling with prior experience in applying these techniques to process, analyze and draw insights from complex datasets involving chemical\n\ncompound structures and toxicity endpoints\n\n• Demonstrated programming proficiency in Python (and/or R) and experience in utilizing machine learning libraries\n\n• Demonstrated in-depth knowledge in toxicology, chemistry, chemical structure, QSAR, drug design, metabolism and ADMET\n\n• Experience in using ADMET modelling platform such as ADMET Predictor is preferred\n\n• Demonstrated teamwork and project leadership skills to manage multiple projects on different timelines for stakeholders across the business\n\n• Excellent communication and presentation skills to different stakeholder audiences\n\nBelow is the brief introduction of SPECTRAFORCE, the benefits we offer and the disclaimers:\n\nEstablished in 2004, SPECTRAFORCE is one of the largest and fastest-growing diversity-owned staffing firms in the US. The growth of our company is a direct result of our global client service delivery model that is powered by our state-of-the-art A.I. proprietary talent acquisition platform, robust ISO 9001:2015/ISO 27001 certified processes, and strong and passionate client engaged teams.\n\nWe have built our business by providing talent and project-based solutions, including Contingent, Permanent, and Statement of Work (SOW) services to over 130 clients in the US, Canada, Puerto Rico, Costa Rica, and India. Key industries that we service include Technology, Financial Services, Life Sciences, Healthcare, Telecom, Retail, Utilities and Transportation.\n\nSPECTRAFORCE is built on a concept of “human connection,” defined by our branding attitude of NEWJOBPHORIA®, which is the excitement of bringing joy and freedom to the work lifestyle so our people (and clients) can reach their highest potential. Our entire workflow and teams are trained to cultivate the joy of NEWJOBPHORIA® with candidates and employees throughout their engagement with SPECTRAFORCE. http://www.spectraforce.com\n\nBenefits: SPECTRAFORCE offers ACA compliant health benefits as well as dental, vision, accident, and hospital indemnity insurances. Additional benefits SPECTRAFORCE offers to the eligible employees include commuter benefits, 401K plan with matching and a referral bonus program. SPECTRAFORCE offers unpaid leave as well as paid sick leave when required by law.\n\nEqual Opportunity Employer: SPECTRAFORCE is an equal opportunity employer and does not discriminate against any employee or applicant for employment because of race, religion, color, sex, national origin, age, sexual orientation, gender identity, genetic information, disability or veteran status, or any other category protected by applicable federal, state, or local laws. Please contact Human Resources at nahr@spectraforce.com if you require reasonable accommodation",
    job_is_remote: false,
    job_posted_at_timestamp: 1689105146,
    job_posted_at_datetime_utc: "2023-07-11T19:52:26.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: ["dental_coverage", "health_insurance", "retirement_savings"],
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=jobs&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=jobs&htidocid=J-owA0CXF9QAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-08-10T19:52:26.000Z",
    job_offer_expiration_timestamp: 1691697146,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 36,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: true,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Ph.D. degree in Cheminformatics, Computational Chemistry, Computer Science, Statistics, Bioinformatics, Toxicology, or a related field",
        "3+ years of experience in developing machine learning models and applying cheminformatics and AI for structure-based drug design, toxicology assessment, and metabolism prediction",
        "Strong technical background in machine learning, deep learning, and statistical modeling with prior experience in applying these techniques to process, analyze and draw insights from complex datasets involving chemical",
        "Demonstrated programming proficiency in Python (and/or R) and experience in utilizing machine learning libraries",
        "Demonstrated in-depth knowledge in toxicology, chemistry, chemical structure, QSAR, drug design, metabolism and ADMET",
        "Demonstrated teamwork and project leadership skills to manage multiple projects on different timelines for stakeholders across the business",
        "Excellent communication and presentation skills to different stakeholder audiences",
      ],
      Responsibilities: [
        "Develop and apply chemistry structure-based predictive models for assessing safety profiles of early stage discovery molecules",
        "Work collaboratively with internal and external cross-functional multidisciplinary teams, collaborators, and consultants to implement in silico models to meet business needs",
        "Serve as a subject matter expert on in silico modelling for the team and other partners in R&D sub-functions",
        "Present the development and application of cheminformatics approaches and novel ML/DL models internally and externally including scientific conferences",
        "Keep abreast of the latest scientific development in the areas of machine learning, cheminformatics, and related fields and identify technologies to be applied internally",
        "Provide mentorship and coaching to team members on in silico modelling and applications",
        "Promote sharing of information and a team-oriented spirit of collaboration",
        "Analyze complex datasets using machine learning approaches and interpret results to improve data-driven decision-making processes",
      ],
      Benefits: [
        "Benefits: SPECTRAFORCE offers ACA compliant health benefits as well as dental, vision, accident, and hospital indemnity insurances",
        "Additional benefits SPECTRAFORCE offers to the eligible employees include commuter benefits, 401K plan with matching and a referral bonus program",
        "SPECTRAFORCE offers unpaid leave as well as paid sick leave when required by law",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "19104200",
    job_onet_job_zone: "5",
    job_naics_code: "541511",
    job_naics_name: "Custom Computer Programming Services",
  },
  {
    employer_name: "Apartment List",
    employer_logo:
      "https://assets-global.website-files.com/5d00480bec9646240b29710d/5d0048122bca9316c97205d4_Apartment_List_Logo_RGB.png",
    employer_website: "http://www.apartmentlist.com",
    employer_company_type: null,
    job_publisher: "Glynn Capital",
    job_id: "Jx2CwtnXnYcAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Sr. Product Analyst",
    job_apply_link:
      "https://jobs.glynncapital.com/companies/apartment-list/jobs/27623509-sr-product-analyst",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.499,
    job_description:
      "At Apartment List, we’re on a mission to find every renter a home they love at the value they deserve. Finding the right place to live is one of the most important, time-consuming and expensive decisions that all of us make. Getting it right matters. We’ve helped nearly 1 million families find a home they love, and we’re just getting started.\n\nWe’re passionate about building a world-class sales team, as we believe that exceptionally talented people are the key to delivering a great customer experience at every turn. We provide a unique opportunity to grow by being surrounded by a team of brilliant and experienced individuals and leaders.\n\nOur team is dedicated to cultivating personal and professional development by creating a culture of feedback, transparency, innovation, passion, learning, and winning. Our business is dependent on happy clients who understand and participate in the Apartment List vision. We are seeking a tenacious team member to join the sales team who loves evangelizing a disruptive, new real estate marketplace advertising opportunity and wants to be part of a growing, evolving team.\n\nAt Apartment List, we’re on a mission to find every renter a home they love at the value they deserve. Finding the right place to live is one of the most important, time-consuming and expensive decisions that all of us make. Getting it right matters. We’ve helped nearly 1 million families find a home they love, and we’re just getting started.\n\nAs a Sr. Product Analyst, you will partner with cross functional teams (engineering, PM, and design) to deliver insights and features that support the renter journey throughout our platform and to develop best-in-class measurement of the business impact of features.\n\nHere’s what you’ll do as part of the team:\n• Join renter experience team and analyze user behavior, developing strategic insights informing experiment design and defining KPIs for features designed to help renters find properties they love.\n• Pull, clean, analyze, and transform data to understand business performance and communicate findings to stakeholders.\n• Design experiments, analyze user behavior to drive thoughtful and strategic decision making on our product team.\n\nHere are the skills and experience you’ll need to be successful:\n• Bachelor’s degree in CS, Math, Statistics, Innovation or similar discipline\n• Min. 3+ years in job offered or in a similar data analytics/scientist role\n• Successful technical screening.\n• This role requires one with strong data narrative communication skills, A/B testing background and expertise in SQL and data wrangling.\n\nHere's the Pay Range:\n\nAt Apartment List, we carefully consider a variety of factors to determine compensation for each position, including the role, level, and work. The US base salary range for this position is $126,277 - $150,000. Please note, the compensation details reflect base salary only and do not include bonus, benefits, and perks that we offer.\n\nWe also rely on market indicators along with considering your work location, job related skills, experience and relevant education and training, to determine compensation that is fair and competitive for you. Apartment List will consider paying compensation near the higher of the range in exceptional circumstances, where candidates have the experience, credentials or expertise that would warrant such consideration. It is always our goal to hire exceptional talent and we would be happy to share more about compensation during the hiring process.\n\nHere's what's in it for you (full-time employees only):\n• Competitive Compensation: Including annual salary, pre-IPO stock options, and other financial compensation (if applicable)\n• Medical, Dental, and Vision Coverage: 100% of premiums covered for you AND all of your dependents\n• Unlimited Flexible Time Off: Unlimited FTO in addition to 11 company holidays per year, quarterly “recharge” days, and a week-long holiday break\n• Home Office Reimbursement: To cover home office furniture and supplies, monthly home internet, and monthly cell phone (if applicable)\n• Health & Wellness Reimbursement: To cover monthly gym membership or other qualifying expenses\n• Parental Support: Generous parental and family leave, fertility benefits, and employer-sponsored stipends towards family forming services\n• 401k Plan: To support you in your individual retirement goals\n• Team Events: Frequent team-building events, fun team off-sites, and bi-annual company meetups (ski trip, etc.)\n• Commitment to DEI: To prioritize Diversity, Equity, and Inclusion within our workplace and to stay true to our values and mission\n• Mentorship and Training: To get you onboard quickly, learn new professional skills, and invest in your career development\n• Impact and Visibility: To expose you to and provide the opportunity to work on highly strategic initiatives that will transform the business\n• Encouragement and Empowerment: To explore and adopt new technologies and drive meaningful decisions and outcomes\n\nAt Apartment List we believe that everyone deserves a home they love AND a career they love. We strive to build a diverse team that is a reflection of the people we serve; this is made possible through our commitment to fostering a culture of diversity, inclusion, equity, and connectedness.\n\nAs a proud equal opportunity employer, we celebrate the collection of individual differences, life experiences, ideas, perspectives, knowledge, and talent. We hire candidates of any race, color, ancestry, religion, sex, national origin, sexual orientation, gender identity, age, marital or family status, disability, Veteran status, and any other status.",
    job_is_remote: true,
    job_posted_at_timestamp: 1689073746,
    job_posted_at_datetime_utc: "2023-07-11T11:09:06.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: [
      "dental_coverage",
      "retirement_savings",
      "paid_time_off",
      "health_insurance",
    ],
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=jobs&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=jobs&htidocid=Jx2CwtnXnYcAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Bachelor’s degree in CS, Math, Statistics, Innovation or similar discipline",
        "3+ years in job offered or in a similar data analytics/scientist role",
        "Successful technical screening",
        "This role requires one with strong data narrative communication skills, A/B testing background and expertise in SQL and data wrangling",
      ],
      Responsibilities: [
        "Product Analyst, you will partner with cross functional teams (engineering, PM, and design) to deliver insights and features that support the renter journey throughout our platform and to develop best-in-class measurement of the business impact of features",
        "Join renter experience team and analyze user behavior, developing strategic insights informing experiment design and defining KPIs for features designed to help renters find properties they love",
        "Pull, clean, analyze, and transform data to understand business performance and communicate findings to stakeholders",
        "Design experiments, analyze user behavior to drive thoughtful and strategic decision making on our product team",
      ],
      Benefits: [
        "The US base salary range for this position is $126,277 - $150,000",
        "Please note, the compensation details reflect base salary only and do not include bonus, benefits, and perks that we offer",
        "We also rely on market indicators along with considering your work location, job related skills, experience and relevant education and training, to determine compensation that is fair and competitive for you",
        "Competitive Compensation: Including annual salary, pre-IPO stock options, and other financial compensation (if applicable)",
        "Medical, Dental, and Vision Coverage: 100% of premiums covered for you AND all of your dependents",
        "Unlimited Flexible Time Off: Unlimited FTO in addition to 11 company holidays per year, quarterly “recharge” days, and a week-long holiday break",
        "Home Office Reimbursement: To cover home office furniture and supplies, monthly home internet, and monthly cell phone (if applicable)",
        "Health & Wellness Reimbursement: To cover monthly gym membership or other qualifying expenses",
        "Parental Support: Generous parental and family leave, fertility benefits, and employer-sponsored stipends towards family forming services",
        "401k Plan: To support you in your individual retirement goals",
        "Team Events: Frequent team-building events, fun team off-sites, and bi-annual company meetups (ski trip, etc.)",
        "Mentorship and Training: To get you onboard quickly, learn new professional skills, and invest in your career development",
      ],
    },
    job_job_title: "Product analyst",
    job_posting_language: "en",
    job_onet_soc: "13116100",
    job_onet_job_zone: "4",
  },
  {
    employer_name: "AT&T",
    employer_logo:
      "https://www.att.com/shopcms/media/att/2014/global/social-logo/logo-att-color-trans-200x200.png",
    employer_website: "https://www.att.com",
    employer_company_type: "Information",
    job_publisher: "JobServe",
    job_id: "In41WGas5QAAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Bilingual Spanish Field Sales Representative",
    job_apply_link:
      "https://www.jobserve.com/gb/en/search-jobs-in-Duluth,-Georgia,-USA/BILINGUAL-SPANISH-FIELD-SALES-REPRESENTATIVE-68BD9A905BE93FD161/",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5487,
    job_description:
      "Join an elite group of sellers bringing customized, white glove experiences directly to the customer's door. Field Sales Representatives at AT&T are driven to connect -every interaction is an opportunity to introduce the latest technology and services, thriving on the challenge to make your sales goals happen. With uncapped commission potential, your career and the rewards that come with it are within reach.\n\nYou'll be the face and voice of AT&T to your customers -and with that comes the autonomy to organize your day to meet customers at the time and place that enhances the personalized sales interactions you create. You'll close the deal by offering hands-on demos, WiFi assessments, tech delivery and issue resolutions -keeping customers connected to what matters most to them. How you get the job done\n• We'll kick things off with paid training -setting you up for success to work independently in the field. Coaching, mentoring and ongoing learning opportunities will keep you on track and tech-savvy.\n• Generate leads -you are ready to take a cold call all the way to the sale while managing and achieving sales targets.\n• You'll use strong negotiation and communications skills -you know how to make a smooth pivot, and are highly motivated to get it right and make the sale Key expectations to succeed\n• Some prior sales experience - preferably in an environment with set targets\n• Maintain a valid driver's license - a big perk of this job is the company car we provide, make sure you're ready to drive.\n• Work a varied schedule designed to meet customers on their timeline -this may include evenings, weekends and holidays.\n• Utilize required PPE and adhere to all safety measures, including basic sanitizing procedures.\n\nOur Field Sales Representatives earn between $41,000 - $61,100 + up to $20,000 in commissions yearly if all sales goals are met. Not to mention all the other amazing rewards that working at AT&T offers. Individual starting salary within this range may depend on geography, experience, expertise, and education/training.\n\nJoining our team comes with amazing perks and benefits:\n• Medical/Dental/Vision coverage\n• 401(k) plan\n• Tuition reimbursement program\n• Paid Time Off and Holidays (based on date of hire, at least 23 days of vacation each year and 9 company-designated holidays)\n• Paid Parental Leave\n• Paid Caregiver Leave\n• Additional sick leave beyond what state and local law require may be available but is unprotected\n• Adoption Reimbursement\n• Disability Benefits (short term and long term)\n• Life and Accidental Death Insurance\n• Supplemental benefit programs: critical illness/accident hospital indemnity/group legal\n• Employee Assistance Programs (EAP)\n• Extensive employee wellness programs\n• Employee discounts up to 50% off on eligible AT&T mobility plans and accessories, AT&T Internet (and fiber where available) and AT&T phone\n\nIf you are considering jobs like Direct Sales Representative, Inside/Outside Sales Representative, Residential Sales Representative, Territory Sales Representative or Field Sales Executive - Home Solutions, this career move would be a great fit!\n\nReady to take your career on a new route? Apply today.\n\nAT&T will consider for employment qualified applicants in a manner consistent with the requirements of federal, state and local laws\n\nWe expect employees to be honest, trustworthy, and operate with integrity. Discrimination and all unlawful harassment (including sexual harassment) in employment is not tolerated. We encourage success based on our individual merits and abilities without regard to race, color, religion, national origin, gender, sexual orientation, gender identity, age, disability, marital status, citizenship status, military status, protected veteran status or employment status",
    job_is_remote: false,
    job_posted_at_timestamp: 1689136080,
    job_posted_at_datetime_utc: "2023-07-12T04:28:00.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: [
      "dental_coverage",
      "health_insurance",
      "retirement_savings",
      "paid_time_off",
    ],
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=jobs&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=jobs&htidocid=In41WGas5QAAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-07-26T04:28:00.000Z",
    job_offer_expiration_timestamp: 1690345680,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 41000,
    job_max_salary: 41000,
    job_salary_currency: "USD",
    job_salary_period: "YEAR",
    job_highlights: {
      Qualifications: [
        "Some prior sales experience - preferably in an environment with set targets",
      ],
      Responsibilities: [
        "You'll be the face and voice of AT&T to your customers -and with that comes the autonomy to organize your day to meet customers at the time and place that enhances the personalized sales interactions you create",
        "You'll close the deal by offering hands-on demos, WiFi assessments, tech delivery and issue resolutions -keeping customers connected to what matters most to them",
        "We'll kick things off with paid training -setting you up for success to work independently in the field",
        "Generate leads -you are ready to take a cold call all the way to the sale while managing and achieving sales targets",
        "You'll use strong negotiation and communications skills -you know how to make a smooth pivot, and are highly motivated to get it right and make the sale Key expectations to succeed",
        "Work a varied schedule designed to meet customers on their timeline -this may include evenings, weekends and holidays",
        "Utilize required PPE and adhere to all safety measures, including basic sanitizing procedures",
      ],
      Benefits: [
        "With uncapped commission potential, your career and the rewards that come with it are within reach",
        "Individual starting salary within this range may depend on geography, experience, expertise, and education/training",
        "Joining our team comes with amazing perks and benefits:",
        "Medical/Dental/Vision coverage",
        "401(k) plan",
        "Tuition reimbursement program",
        "Paid Time Off and Holidays (based on date of hire, at least 23 days of vacation each year and 9 company-designated holidays)",
        "Paid Parental Leave",
        "Paid Caregiver Leave",
        "Additional sick leave beyond what state and local law require may be available but is unprotected",
        "Adoption Reimbursement",
        "Disability Benefits (short term and long term)",
        "Life and Accidental Death Insurance",
        "Supplemental benefit programs: critical illness/accident hospital indemnity/group legal",
        "Employee Assistance Programs (EAP)",
        "Extensive employee wellness programs",
        "Employee discounts up to 50% off on eligible AT&T mobility plans and accessories, AT&T Internet (and fiber where available) and AT&T phone",
      ],
    },
    job_job_title: "Sales representative",
    job_posting_language: "en",
    job_onet_soc: "41401200",
    job_onet_job_zone: "4",
    job_naics_code: "517110",
    job_naics_name: "Wired Telecommunications Carriers",
  },
  {
    employer_name: "Beeline",
    employer_logo:
      "https://mma.prnewswire.com/media/525059/Beeline_Logo.jpg?p=facebook",
    employer_website: "http://www.beeline.com",
    employer_company_type: "Computer Services",
    job_publisher: "Salary.com",
    job_id: "RsvBOGwh8xAAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Project Manager",
    job_apply_link:
      "https://www.salary.com/job/beeline/project-manager/j202307110132218661670",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5513,
    job_description:
      'Project Manager\n\nPurpose of the Position : The Project Manager will be working with the project delivery team members to help large and complex enterprise organizations transform their business while implementing Beeline solutions. Successful candidates must be able to manage a highly complex project within the specified timeline and budget to meet the requirements of the client successfully. It is also critical that this individual be skilled at managing issues and mitigating risks as it relates to the delivery of the implementation. Successful candidates will be able to demonstrate an understanding that both external and internal project teams are their customer.\n\nLocation: This is a UK based fully remote based opportunity (some travel to client sites in UK and Europe may be required on an ad-hoc basis)\n\nResponsibilities :\n\n· Deliver high level presentations to audiences ranging from executives to system end users.\n\n· Drive end to end projects in collaboration with client project manager to a successful deployment of the Beeline solutions.\n\n· Act as the key liaison and business partner to the client at both the project management and executive level as needed.\n\n· Identify resource needs, manage resource time allocation, and hold team accountable to deadlines.\n\n· Create and manage the project plan, focusing on maintaining project timelines and ensuring milestones are met.\n\n· Manage issues and risk by clearly communicating both internally and externally, escalating as needed and deploying risk mitigation strategies as appropriate.\n\n· Reporting on available resources, budget, and project status to project sponsors and stakeholders\n\n· Ability to work on multiple, concurrent tasks and adapt to shifting priorities, demands and timelines.\n\n· Effective communication and teamwork with project teams and collaboration with other departments\n\n· Understand priorities, scope, timeline, goals, and key milestones.\n\n· Maintain customer focus and demonstrate leadership to drive consensus and project related decisions.\n\n· Manage client expectations appropriately with the ability to manage through challenging situations with positive outcomes.\n\nRequirements :\n\n· Bachelor’s degree or equivalent work experience\n\n· 5 years’ experience working in a professional service setting implementing software projects for external clients.\n\nDesired Competencies :\n\n· Proficient at developing and managing project schedules\n\n· Experience managing a project team that includes business and technical consultants.\n\n· Excellent written and verbal communication skills.\n\n· Ability to multitask on concurrent projects and deliver work on time and under budget.\n\n· Engaged and confident presence with client- one who can establish and sustain credibility and trust.\n\n· Ability and desire to drive change through high-energy, can-do attitude, comfortable working in a high-performance, entrepreneurial, open-door environment.\n\n· Must be an outstanding communicator and team player who demonstrates attention to detail\n\n· Strong analytical and problem-solving skills\n\n· Ability to work autonomously.\n\nOur Company: At Beeline, we cultivate a positive work environment and are passionate about who we are and what we do. We are a 20-year industry leader disrupting the world of external workforce technology. Businesses across all industries use our technology to manage more than 30 million workers and over $700 billion in talent spend across 120 countries. Ideal candidates are intensely curious about technology, thrive in a less-than-formal work environment, and excel in a fast-paced, rapidly changing environment. We are looking for talented, driven, and adaptable people who will contribute to our vision, mission, and our future!\n\nOur Vision : Every person, given the right opportunity, is capable of greatness. Every business, given the right talent, is capable of superior outcomes.\n\nOur Mission : Our trusted platform connects businesses to the remarkable talent within the global extended workforce.\n\nTo learn more about Beeline, our solutions, our culture, and available positions visit https://www.beeline.com/.\n\nThis list of "Requirements and Responsibilities" is not intended to be limiting. The Company reserves the right to revise this job description based on the actual job requirements as varied from time to time.\n\nEqual Opportunity Employer Minorities/Women/Veterans/Disabled',
    job_is_remote: false,
    job_posted_at_timestamp: 1689120000,
    job_posted_at_datetime_utc: "2023-07-12T00:00:00.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=jobs&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=jobs&htidocid=RsvBOGwh8xAAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2024-01-11T00:00:00.000Z",
    job_offer_expiration_timestamp: 1704931200,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 60,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Bachelor’s degree or equivalent work experience",
        "5 years’ experience working in a professional service setting implementing software projects for external clients",
      ],
      Responsibilities: [
        "Purpose of the Position : The Project Manager will be working with the project delivery team members to help large and complex enterprise organizations transform their business while implementing Beeline solutions",
        "It is also critical that this individual be skilled at managing issues and mitigating risks as it relates to the delivery of the implementation",
        "Location: This is a UK based fully remote based opportunity (some travel to client sites in UK and Europe may be required on an ad-hoc basis)",
        "Deliver high level presentations to audiences ranging from executives to system end users",
        "Drive end to end projects in collaboration with client project manager to a successful deployment of the Beeline solutions",
        "Act as the key liaison and business partner to the client at both the project management and executive level as needed",
        "Identify resource needs, manage resource time allocation, and hold team accountable to deadlines",
        "Create and manage the project plan, focusing on maintaining project timelines and ensuring milestones are met",
        "Manage issues and risk by clearly communicating both internally and externally, escalating as needed and deploying risk mitigation strategies as appropriate",
        "Reporting on available resources, budget, and project status to project sponsors and stakeholders",
        "Ability to work on multiple, concurrent tasks and adapt to shifting priorities, demands and timelines",
        "Effective communication and teamwork with project teams and collaboration with other departments",
        "Understand priorities, scope, timeline, goals, and key milestones",
        "Maintain customer focus and demonstrate leadership to drive consensus and project related decisions",
        "Manage client expectations appropriately with the ability to manage through challenging situations with positive outcomes",
      ],
    },
    job_job_title: "Project manager",
    job_posting_language: "en",
    job_onet_soc: "13108200",
    job_onet_job_zone: null,
    job_naics_code: "541512",
    job_naics_name: "Computer Systems Design Services",
  },
];
