export default [
  {
    employer_name: "Accenture",
    employer_logo:
      "https://dynamicmedia.accenture.com/is/image/accenture/Acc_Logo_Black_Purple_RGB?qlt=85&ts=1686906002905&dpr=off",
    employer_website: "http://www.accenture.com",
    employer_company_type: "Computer Services",
    job_publisher: "LinkedIn",
    job_id: "6-4kLy-mzjEAAAAAAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "Salesforce Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/salesforce-developer-at-accenture-3653656856",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5622,
    job_description:
      "ACCENTURE's Flexible Workforce solves clients’ toughest challenges by providing cross-industry expertise, unmatched innovation, World-class tech and talent. We help bring it all together to deliver tangible business outcomes for our clients with contractors and our extended workforce opportunities. Accenture is consistently recognized on FORTUNE’s 100 Best Companies to Work for and Diversity Inc’s Top 50 Companies for Diversity lists. And that's just the beginning. Now is the perfect time for you to consider opportunities through our Flexible Workforce.\n\nWhat's In It For You\n• Collaborate with a diverse network of people\n• Actively deliver innovative solutions for Accenture's clients\n• Apply your skills and experience to help drive business transformation\n• Work locally or remotely, significantly reducing or eliminating the demands to travel\nProject Description:\n• We are seeking a Salesforce Application Developer in Raleigh, NC will work remotely and then onsite once the restrictions are lifted.\n• This is a 12 months contract opportunity that does not offer sponsorship or in the future.\n• Must be able to work on W2.\n\nResponsibilities\n• Salesforce Service Cloud: Provide support lead responsibilities for the application built on Salesforce Service Cloud.\n• Must have 5-8 years of experience in Salesforce Service Cloud code customization.\n• Must have good knowledge and experience in Salesforce integration using REST API.\n• Good to have experience and knowledge on Salesforce Community portal.\n• Provide support service to client under the SLA - 18X5 along with minor releases (monthly releases).\n• Good to have any knowledge in Life Science domain with Veeva CRM and Veeva Network Bridge.\n• Manage and able to coordinate offshore team as a single point of contact for escalation, client communications.\n• Provide communication to client on major incidents, outage, root cause analysis.\n• Single point of escalation for Patient Services program (Salesforce based and integration areas).\n• Should be good in communication skills (Verbal and written).\n• Certification in Salesforce Service Cloud (PD1/2, App Developer, Service Cloud with higher proficiency.\n• Must be online in the system from 8 am to 5 pm EST hours to support production issues.\n• In case of any P1 or P2 incidents, we expect to provide support for the resolution.\n• Experience in Build Configuration & Release Management ,Design & Build Enablement and Salesforce Community Cloud.\n• Must Have Salesforce Service Cloud ,Salesforce Community Portal ,REST API integration with Salesforce.\n• Must have 1. 5 to 8 years in Salesforce Service Cloud and Community portal (together).\n• Must have 0 to 3 years in REST API Integration.\n• Nice to Have REST API Integration in Salesforce and Salesforce Health cloud.\n• Participate in client calls and technical discussions.\n• Able to work independently on technical issues.\n• Available for client each day between 8 am and 5 pm EST / EDT .\n• Provide daily status to Accenture and Biogen leads .\n• Help offshore team in resolving complex issues.\n• Coordinate with IT and Business team for clarifications and closures\n\nBasic Qualifications\n• Bachelor's Degree\n\nBonus Points If You Have\n• Master's Degree\n\nKeywords: Salesforce, Application Developer, Cloud\n\nWhat We Believe\n\nWe have an unwavering commitment to diversity with the aim that every one of our people has a full sense of belonging within our organization. As a business imperative, every person at Accenture has the responsibility to create and sustain an inclusive environment.\n\nInclusion and diversity are fundamental to our culture and core values. Our rich diversity makes us more innovative and more creative, which helps us better serve our clients and our communities. Read more here\n\nEqual Employment Opportunity Statement\n\nAccenture is an Equal Opportunity Employer. We believe that no one should be discriminated against because of their differences, such as age, disability, ethnicity, gender, gender identity and expression, religion or sexual orientation. Our rich diversity makes us more innovative, more competitive and more creative, which helps us better serve our clients and our communities.\n\nAll employment decisions shall be made without regard to age, race, creed, color, religion, sex, national origin, ancestry, disability status, veteran status, sexual orientation, gender identity or expression, genetic information, marital status, citizenship status or any other basis as protected by federal, state, or local law.\n\nAccenture is committed to providing veteran employment opportunities to our service men and women.\n\nFor details, view a copy of the Accenture Equal Opportunity and Affirmative Action Policy Statement\n\nRequesting An Accommodation\n\nAccenture is committed to providing equal employment opportunities for persons with disabilities or religious observances, including reasonable accommodation when needed. If you are hired by Accenture and require accommodation to perform the essential functions of your role, you will be asked to participate in our reasonable accommodation process. Accommodations made to facilitate the recruiting process are not a guarantee of future or continued accommodations once hired.\n\nIf you would like to be considered for employment opportunities with Accenture and have accommodation needs for a disability or religious observance, please call us toll free at 1 (877) 889-9009, send us an email or speak with your recruiter.\n\nOther Employment Statements\n\nApplicants for employment in the US must have work authorization that does not now or in the future require sponsorship of a visa for employment authorization in the United States.\n\nCandidates who are currently employed by a client of Accenture or an affiliated Accenture business may not be eligible for consideration.\n\nJob candidates will not be obligated to disclose sealed or expunged records of conviction or arrest as part of the hiring process.\n\nThe Company will not discharge or in any other manner discriminate against employees or applicants because they have inquired about, discussed, or disclosed their own pay or the pay of another employee or applicant. Additionally, employees who have access to the compensation information of other employees or applicants as a part of their essential job functions cannot disclose the pay of other employees or applicants to individuals who do not otherwise have access to compensation information, unless the disclosure is (a) in response to a formal complaint or charge, (b) in furtherance of an investigation, proceeding, hearing, or action, including an investigation conducted by the employer, or (c) consistent with the Company's legal duty to furnish information.",
    job_is_remote: true,
    job_posted_at_timestamp: 1688826303,
    job_posted_at_datetime_utc: "2023-07-08T14:25:03.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=developer+jobs&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=developer+jobs&htidocid=6-4kLy-mzjEAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-08-07T14:25:03.000Z",
    job_offer_expiration_timestamp: 1691418303,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 60,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: false,
      professional_certification_mentioned: true,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Must be able to work on W2",
        "Bachelor's Degree",
        "Master's Degree",
        "Applicants for employment in the US must have work authorization that does not now or in the future require sponsorship of a visa for employment authorization in the United States",
      ],
      Responsibilities: [
        "Salesforce Service Cloud: Provide support lead responsibilities for the application built on Salesforce Service Cloud",
        "Must have 5-8 years of experience in Salesforce Service Cloud code customization",
        "Provide support service to client under the SLA - 18X5 along with minor releases (monthly releases)",
        "Good to have any knowledge in Life Science domain with Veeva CRM and Veeva Network Bridge",
        "Manage and able to coordinate offshore team as a single point of contact for escalation, client communications",
        "Provide communication to client on major incidents, outage, root cause analysis",
        "Single point of escalation for Patient Services program (Salesforce based and integration areas)",
        "Should be good in communication skills (Verbal and written)",
        "Must be online in the system from 8 am to 5 pm EST hours to support production issues",
        "In case of any P1 or P2 incidents, we expect to provide support for the resolution",
        "Experience in Build Configuration & Release Management ,Design & Build Enablement and Salesforce Community Cloud",
        "Must Have Salesforce Service Cloud ,Salesforce Community Portal ,REST API integration with Salesforce",
        "Must have 1. 5 to 8 years in Salesforce Service Cloud and Community portal (together)",
        "Nice to Have REST API Integration in Salesforce and Salesforce Health cloud",
        "Participate in client calls and technical discussions",
        "Able to work independently on technical issues",
        "Available for client each day between 8 am and 5 pm EST / EDT ",
        "Provide daily status to Accenture and Biogen leads ",
        "Help offshore team in resolving complex issues",
        "Coordinate with IT and Business team for clarifications and closures",
      ],
      Benefits: ["Collaborate with a diverse network of people"],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
    job_naics_code: "541511",
    job_naics_name: "Custom Computer Programming Services",
  },
  {
    employer_name: "Infinite Computer Solutions",
    employer_logo:
      "https://www.infinite.com/wp-content/uploads/2023/04/Infinite.jpg",
    employer_website: "http://www.infinite.com",
    employer_company_type: "Computer Services",
    job_publisher: "LinkedIn",
    job_id: "MwRaVtg3c_cAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Lead React Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/lead-react-developer-at-infinite-computer-solutions-3653636443",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.6025,
    job_description:
      "Number of positions - 4\n• Primary skills we're looking for: React, Redux, NodeJs and Express, HTML, JS, CSS, SASS, web pack (bundling libraries)\n• Secondary skills: Sinon (for unit testing), wedriver.io (for UI test), grunt and screwdriver (for build), github, GCP/cloud technologies, Babel, and NPM",
    job_is_remote: false,
    job_posted_at_timestamp: 1688808737,
    job_posted_at_datetime_utc: "2023-07-08T09:32:17.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=developer+jobs&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=developer+jobs&htidocid=MwRaVtg3c_cAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-08-07T09:32:17.000Z",
    job_offer_expiration_timestamp: 1691400737,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: false,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Primary skills we're looking for: React, Redux, NodeJs and Express, HTML, JS, CSS, SASS, web pack (bundling libraries)",
        "Secondary skills: Sinon (for unit testing), wedriver.io (for UI test), grunt and screwdriver (for build), github, GCP/cloud technologies, Babel, and NPM",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
    job_naics_code: "541512",
    job_naics_name: "Computer Systems Design Services",
  },
  {
    employer_name: "LVI Associates",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyLS_9Dgm-Ijuv0efZSkgcGSnnn7CFR1WOCDvI&s=0",
    employer_website: "http://www.lviassociates.com",
    employer_company_type: null,
    job_publisher: "LVI Associates",
    job_id: "26FBoDCbOkAAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Project Developer",
    job_apply_link: "https://www.lviassociates.com/job/project-developer-10",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.8638,
    job_description:
      "Project Developer\n\nSummary: My client is a newly formed company focused on greenfield development in the community solar space. They will be looking into largely undeveloped markets, that are not historically known for their community solar presence.\n\nThe Project Developer will be responsible for…\n• Entire greenfield development lifecycle from start to finish including but not limited to, environmental site assessments, site selection and acquisition, permitting, and contract negotiations.\n• Identifying, pursuing, and qualifying solar projects through regulatory research and market analysis/trends.\n• Engage with landowners and local community to keep them informed throughout the development process.\n\nThe Project Developer should have the following qualifications…\n• Bachelor's degree in Engineering, Environmental, Business Administration or Economics preferred.\n• Experience with the full greenfield project development lifecycle.\n• A focused, strategic individual who is very initial about where and what projects they are working on.",
    job_is_remote: false,
    job_posted_at_timestamp: 1688757382,
    job_posted_at_datetime_utc: "2023-07-07T19:16:22.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=developer+jobs&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=developer+jobs&htidocid=26FBoDCbOkAAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-09-05T23:59:59.000Z",
    job_offer_expiration_timestamp: 1693958399,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Experience with the full greenfield project development lifecycle",
        "A focused, strategic individual who is very initial about where and what projects they are working on",
      ],
      Responsibilities: [
        "The Project Developer will be responsible for…",
        "Entire greenfield development lifecycle from start to finish including but not limited to, environmental site assessments, site selection and acquisition, permitting, and contract negotiations",
        "Identifying, pursuing, and qualifying solar projects through regulatory research and market analysis/trends",
        "Engage with landowners and local community to keep them informed throughout the development process",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "13108200",
    job_onet_job_zone: null,
  },
  {
    employer_name: "Optomi",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTt2N5vGORr23wYN4mLknOWhiyL0PU0VLLGkse&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "11OL_vXgaZkAAAAAAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "Angular Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/angular-developer-at-optomi-3653218700",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5486,
    job_description:
      "Angular Developer\n• Must be able to work on W2!!!!\n\nOptomi, in partnership with a leader in the telecommunications industry, is seeking an Angular Developer to join their team! This developer will work 80% on the Front end with Angular and 20% on the backend with Python/Django.\n\nWhat the right Professional Will Enjoy!\n• The opportunity to work with a leading telecommunications company!\n• The opportunity to work on cutting-edge Technology!\n• Work with a creative team and be a part of an exciting culture!\n\nMust Have Skills/ Requirements:\n• Angular\n• Python/Django\n• JavaScript/TypeScript\n\nNice to Have Skills:\n• React\n• MySQL",
    job_is_remote: true,
    job_posted_at_timestamp: 1688748570,
    job_posted_at_datetime_utc: "2023-07-07T16:49:30.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=developer+jobs&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=developer+jobs&htidocid=11OL_vXgaZkAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-08-06T16:49:30.000Z",
    job_offer_expiration_timestamp: 1691340570,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: false,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Must be able to work on W2!!!!",
        "Work with a creative team and be a part of an exciting culture!",
        "Python/Django",
        "JavaScript/TypeScript",
        "React",
        "MySQL",
      ],
      Benefits: [
        "The opportunity to work with a leading telecommunications company!",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
  },
  {
    employer_name: "Upwork",
    employer_logo: "https://image.status.io/z6aeO6kAGsAG.png",
    employer_website: "http://www.elance.com",
    employer_company_type: "Computer Services",
    job_publisher: "Upwork",
    job_id: "FlJHJJ2e0ggAAAAAAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "Easy Unity Developer Job",
    job_apply_link:
      "https://www.upwork.com/en-gb/freelance-jobs/apply/Easy-Unity-Developer-Job_~01d03a947e52a0a686/",
    job_apply_is_direct: true,
    job_apply_quality_score: 0.7802,
    job_description:
      "Each Prefab level does randomly assemble in game, but one random level gets spawned twice, which it should not. Each prefab level should have a probability value so I can choose which level shows up first. For example, I want some easy levels to show on level 1, but still one of the hard level will have a very small chance that it will show up first too. These should somehow be set with a variable and there should be an option where I can make prefab permanently show at a specific level. Will provide ScreenManger and StageManger script. Also, I need you to make make main screen and loading screen script. I will add assets over my side. Guid me to add screen to rewarded button. Add background music and sound effect to buttons, I will add specific sounds myself.",
    job_is_remote: true,
    job_posted_at_timestamp: 1688530855,
    job_posted_at_datetime_utc: "2023-07-05T04:20:55.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=developer+jobs&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=developer+jobs&htidocid=FlJHJJ2e0ggAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: false,
      experience_preferred: false,
    },
    job_required_skills: ["Unity", "C#"],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Responsibilities: [
        "For example, I want some easy levels to show on level 1, but still one of the hard level will have a very small chance that it will show up first too",
        "These should somehow be set with a variable and there should be an option where I can make prefab permanently show at a specific level",
        "Will provide ScreenManger and StageManger script",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
    job_naics_code: "541511",
    job_naics_name: "Custom Computer Programming Services",
  },
  {
    employer_name: "RD SOLUTIONS INC",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2p74sk_2sGPG2wuHR1Yc2wt1WIHPrzPmcVWJA&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "jJ9woHso0S0AAAAAAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "Centura Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/centura-developer-at-rd-solutions-inc-3653236274",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.595,
    job_description:
      "Centura Developer:\n\nCentura Team Developer, formerly known as Gupta Team Developer or SQLWindows, is a development environment and programming language used for building client-server and web applications. A Centura Team Developer job description may include the following responsibilities and qualifications:\n\nJob Description:\n• Designing, coding, and debugging applications using Centura Team Developer.\n• Collaborating with business analysts and stakeholders to gather requirements and translate them into technical specifications.\n• Developing and maintaining software applications, including user interfaces, business logic, and database integration.\n• Writing efficient and well-structured code in Centura Team Developer programming language.\n• Conducting unit testing and debugging to ensure the applications meet functional requirements and are free from errors.\n• Optimizing application performance and responsiveness.\n• Working with relational databases (e.g., Oracle, SQL Server, MySQL) and implementing database operations such as querying, data manipulation, and reporting.\n• Integrating applications with web services and other third-party systems.\n• Following coding standards and best practices to ensure high-quality code and maintainable software.\n• Documenting application designs, code, and system configurations.\n• Collaborating with cross-functional teams, including testers, system administrators, and project managers, to ensure successful project delivery.\n• Keeping up to date with the latest Centura Team Developer updates, technologies, and industry trends.\n• Providing technical support and troubleshooting assistance to end-users.\n\nQualifications:\n• Bachelor's degree in Computer Science, Software Engineering, or a related field.\n• Solid experience in developing applications using Centura Team Developer or Gupta Team Developer.\n• Proficiency in Centura Team Developer programming language and associated development tools.\n• Strong knowledge of client-server architecture and web application development concepts.\n• Familiarity with relational databases and SQL.\n• Experience in software development life cycle (SDLC) methodologies and practices.\n• Problem-solving skills and attention to detail in debugging and resolving issues.\n• Good understanding of software development principles and best practices.\n• Excellent communication and teamwork skills.\n• Ability to work independently and handle multiple tasks simultaneously.",
    job_is_remote: true,
    job_posted_at_timestamp: 1688752905,
    job_posted_at_datetime_utc: "2023-07-07T18:01:45.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=developer+jobs&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=developer+jobs&htidocid=jJ9woHso0S0AAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-08-06T18:01:45.000Z",
    job_offer_expiration_timestamp: 1691344905,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Bachelor's degree in Computer Science, Software Engineering, or a related field",
        "Solid experience in developing applications using Centura Team Developer or Gupta Team Developer",
        "Proficiency in Centura Team Developer programming language and associated development tools",
        "Strong knowledge of client-server architecture and web application development concepts",
        "Familiarity with relational databases and SQL",
        "Experience in software development life cycle (SDLC) methodologies and practices",
        "Problem-solving skills and attention to detail in debugging and resolving issues",
        "Good understanding of software development principles and best practices",
        "Excellent communication and teamwork skills",
        "Ability to work independently and handle multiple tasks simultaneously",
      ],
      Responsibilities: [
        "Designing, coding, and debugging applications using Centura Team Developer",
        "Collaborating with business analysts and stakeholders to gather requirements and translate them into technical specifications",
        "Developing and maintaining software applications, including user interfaces, business logic, and database integration",
        "Writing efficient and well-structured code in Centura Team Developer programming language",
        "Conducting unit testing and debugging to ensure the applications meet functional requirements and are free from errors",
        "Optimizing application performance and responsiveness",
        "Working with relational databases (e.g., Oracle, SQL Server, MySQL) and implementing database operations such as querying, data manipulation, and reporting",
        "Integrating applications with web services and other third-party systems",
        "Following coding standards and best practices to ensure high-quality code and maintainable software",
        "Documenting application designs, code, and system configurations",
        "Collaborating with cross-functional teams, including testers, system administrators, and project managers, to ensure successful project delivery",
        "Keeping up to date with the latest Centura Team Developer updates, technologies, and industry trends",
        "Providing technical support and troubleshooting assistance to end-users",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
  },
  {
    employer_name: "TekNavigators Staffing",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpZH9kVzjiZgdTbpIj4pZT5kxUNX-8TuGwzzBe&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "LinkedIn",
    job_id: "ZfK-4n5xay8AAAAAAAAAAA==",
    job_employment_type: "CONTRACTOR",
    job_title: "OpenFin Web Developer",
    job_apply_link:
      "https://www.linkedin.com/jobs/view/openfin-web-developer-at-teknavigators-staffing-3658606178",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5939,
    job_description:
      "Must have: OpenFin, React, API, HTML, CSS JavaScript\n\nResponsibilities\n• You will build applications that push the envelope when it comes to throughput, latency, resiliency, all the while making sure that we deliver on-time and within budget.\n• Using OpenFin's platform APIs with execution and analytics capabilities.\n\nRequired Skills and Experience\n• 5+ years of commercial-grade web/front-end development experience.\n• Expertise on OpenFin (build on top of ReactJS)\n• Strong experience in JavaScript, ideally ES6 or ES7, building Single Page Web Applications with modern frameworks, preferably using React.\n• Solid skills in HTML5 and CSS3.\n• Knowledge of the Agile Development Methodology.\n• Strong interpersonal and organizational skills.\n• Knowledge of, and keen demonstrated interest in, global financial markets and financial products is a definite plus.\n• Bachelors or Masters in Computer Science, Engineering, Physics, Math, or related work experience.",
    job_is_remote: true,
    job_posted_at_timestamp: 1688768918,
    job_posted_at_datetime_utc: "2023-07-07T22:28:38.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=developer+jobs&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=developer+jobs&htidocid=ZfK-4n5xay8AAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-08-06T22:28:38.000Z",
    job_offer_expiration_timestamp: 1691360918,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 60,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: true,
      degree_mentioned: true,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "5+ years of commercial-grade web/front-end development experience",
        "Expertise on OpenFin (build on top of ReactJS)",
        "Strong experience in JavaScript, ideally ES6 or ES7, building Single Page Web Applications with modern frameworks, preferably using React",
        "Solid skills in HTML5 and CSS3",
        "Knowledge of the Agile Development Methodology",
        "Strong interpersonal and organizational skills",
        "Knowledge of, and keen demonstrated interest in, global financial markets and financial products is a definite plus",
        "Bachelors or Masters in Computer Science, Engineering, Physics, Math, or related work experience",
      ],
      Responsibilities: [
        "You will build applications that push the envelope when it comes to throughput, latency, resiliency, all the while making sure that we deliver on-time and within budget",
        "Using OpenFin's platform APIs with execution and analytics capabilities",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
  },
  {
    employer_name: "GE",
    employer_logo:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/General_Electric_logo.svg/1200px-General_Electric_logo.svg.png",
    employer_website: "http://www.ge.com",
    employer_company_type: "Manufacturing",
    job_publisher: "GE Careers",
    job_id: "RETLI-51f6AAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Sr. Software Developer",
    job_apply_link:
      "https://jobs.gecareers.com/healthcare/global/en/job/R3713967/Sr-Software-Developer",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.7865,
    job_description:
      "Job Description Summary\n\nJob Description\n\nCaption Health’s mission is to detect disease early – when there is the highest potential for impact – by leveraging artificial intelligence and ultrasound. Our breakthrough AI platform enables any healthcare professional to perform high-quality ultrasound exams for early disease detection, in convenient and lower-cost outpatient settings including patients’ homes. It was recognized as one of TIME’s 100 Best Inventions of 2021 and one of Fast Company’s Next Big Things in Health Tech. Through our work with health plans, providers, patients, and industry partners, we are transforming care, expanding access, and reducing costs.\n\nThe SKD and Application Developer integrates Caption Health’s AI-enabled features into world-class ultrasound systems running on iOS, Android, and Windows.\n\nLocation: Remote/work from home\n\nDuties/Responsibilities:\n• Implement new ultrasound features in the Caption Health SDK.\n• Port machine learning models and algorithms into the SDK.\n• Support the SDK across multiple architectures, including iOS, Android, and Windows.\n• Integrate the SDK into existing world-class ultrasound systems.\n• Implement UI features using iOS, Android, and/or Qt frameworks.\n• Provides guidance to technical and non-technical users effectively and efficiently.\n• Identifies potential process improvement areas and suggests enhancements.\n• Perform other duties as assigned.\n\nRequired Skills/Abilities:\n• Strong coding skills in C++.\n• Experience with cross-platform, client-side development\n• Experience developing APIs and SDKs.\n• Experience with development on iOS, Android, or Qt is a plus.\n• Experience with Python is a plus.\n• Strong collaboration and communication skills.\n\nEducation and Experience:\n• Bachelor's degree in Software Engineering or related technical field.\n• 4+ years' programming experience.\n• Familiarity with crafting modular APIs.\n\nPhysical Requirements:\n• Prolonged periods of sitting at a desk and working on a computer.\n\nWe expect all employees to live and breathe our behaviors: to act with humility and build trust; lead with transparency; deliver with focus, and drive ownership –always with unyielding integrity.\n\nOur total rewards are designed to unlock your ambition by giving you the boost and flexibility you need to turn your ideas into world-changing realities. Our salary and benefits are everything you’d expect from an organization with global strength and scale, and you’ll be surrounded by career opportunities in a culture that fosters care, collaboration and support.\n\nWhile GE Healthcare does not currently require U.S. employees to be vaccinated against COVID-19, some GE Healthcare customers have vaccination mandates that may apply to certain GE Healthcare employees.\n\nGE offers a great work environment, professional development, challenging careers, and competitive compensation. GE is an Equal Opportunity Employer. Employment decisions are made without regard to race, color, religion, national or ethnic origin, sex, sexual orientation, gender identity or expression, age, disability, protected veteran status or other characteristics protected by law.\n\nGE will only employ those who are legally authorized to work in the United States for this opening. Any offer of employment is conditioned upon the successful completion of a drug screen (as applicable).\n\nAdditional Information\n\nGE offers a great work environment, professional development, challenging careers, and competitive compensation. GE is an Equal Opportunity Employer. Employment decisions are made without regard to race, color, religion, national or ethnic origin, sex, sexual orientation, gender identity or expression, age, disability, protected veteran status or other characteristics protected by law.\n\nGE will only employ those who are legally authorized to work in the United States for this opening. Any offer of employment is conditioned upon the successful completion of a drug screen (as applicable).\n\nRelocation Assistance Provided: No",
    job_is_remote: true,
    job_posted_at_timestamp: 1685664000,
    job_posted_at_datetime_utc: "2023-06-02T00:00:00.000Z",
    job_city: null,
    job_state: "OK",
    job_country: "US",
    job_latitude: 35.00775,
    job_longitude: -97.09288,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=developer+jobs&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=developer+jobs&htidocid=RETLI-51f6AAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 48,
      experience_mentioned: true,
      experience_preferred: true,
    },
    job_required_skills: [
      "Programming",
      "Android",
      "SDK",
      "Software Engineering",
      "IOS",
      "UI",
      "Python",
      "qt",
      "Algorithms",
      "qt frameworks",
      "Running",
      "Artificial Intelligence",
      "Machine Learning Models",
      "Integrity",
      "Ownership",
      "collaboration",
      "Potential",
      "Flexibility",
      "Process Improvement",
      "Professional Development",
      "Communication Skills",
      "general office duties",
      "UI Software Developer",
      "Software Developer",
      "Software Engineer & Java Developer",
      "Senior Lead Software Developer",
      "Associate Software Developer",
      "C# & .Net Software Developer",
      "Software Engineer & Java Programmer",
      "Junior Software Developer",
      "Senior Software Developer & Team Lead",
      "Software Test Engineer & Java Developer",
    ],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: null,
    job_max_salary: null,
    job_salary_currency: null,
    job_salary_period: null,
    job_highlights: {
      Qualifications: [
        "Strong coding skills in C++",
        "Experience with cross-platform, client-side development",
        "Experience developing APIs and SDKs",
        "Strong collaboration and communication skills",
        "Bachelor's degree in Software Engineering or related technical field",
        "4+ years' programming experience",
        "Familiarity with crafting modular APIs",
        "Prolonged periods of sitting at a desk and working on a computer",
      ],
      Responsibilities: [
        "Implement new ultrasound features in the Caption Health SDK",
        "Port machine learning models and algorithms into the SDK",
        "Integrate the SDK into existing world-class ultrasound systems",
        "Implement UI features using iOS, Android, and/or Qt frameworks",
        "Provides guidance to technical and non-technical users effectively and efficiently",
        "Identifies potential process improvement areas and suggests enhancements",
        "Perform other duties as assigned",
      ],
      Benefits: [
        "Our salary and benefits are everything you’d expect from an organization with global strength and scale, and you’ll be surrounded by career opportunities in a culture that fosters care, collaboration and support",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113200",
    job_onet_job_zone: "4",
    job_occupational_categories: ["Digital Technology / IT"],
    job_naics_code: "3351",
    job_naics_name: "Electric Lighting Equipment Manufacturing",
  },
  {
    employer_name: "Aleph One Consulting",
    employer_logo: null,
    employer_website: null,
    employer_company_type: null,
    job_publisher: "FROST ME CAFE",
    job_id: "Hmv5o-6TBS4AAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Full Stack Developer",
    job_apply_link:
      "https://frostme.com/.workspread/job/full-stack-developer-at-aleph-one-consulting-remote-SmhRQnNHRUJhWkRic2Z6RnlQWnZCZz09",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.5259,
    job_description:
      "Aleph One Consulting is now hiring Full Stack Developer in Remote. View job listing details and apply now.\n\nWe’re looking for a Mid-Level Full Stack Java Developer to support our government client and become an integral part of our team as well. Join Aleph One Consulting for a rewarding career.\n\nWhy join Aleph One Consulting?\n\nAleph One Consulting is committed to delivering superior digital integration, and management products and practices to our public and commercial sector clients. Our mission is to help our clients and partners identify gaps and insights into their business domain, generate new and exciting ideas, and drive meaningful results to get the most out of their products, portfolios and teams.\n\nWhat are we looking for?\n\nWe’re in need of Mid-Level Full Stack Java Developer to support our government client with Technical Governance activities.\n\nWe’re looking to hire skilled professionals who will be part of our integral team and will possess extensive Java capability, keen leadership skills and the ability to manage a very congenial but challenging government product owner. IOS mobile app development experience would be a bonus. You will need to be capable of communicating technical ideas to our non-technical stakeholders in a simple and understandable way.\n\nWhat do I need to know to apply?\n\nBasic requirements:\n\nCitizenship Status: Must be a US Citizen\n\nDegree: Bachelor’s Degree in Computer Science, Information Technology or related field with coursework in technology-related subjects.\n\nExperience: Minimum of 5-7 years of Java Development Experience\n\nPosition Type: Independent Contractor (1099)\n\nLocation: Remote (Client Site: MD)\n\nJava Specific Requirements:\n\n· Strong working knowledge of Java/J2EE, JPA, Spring, and related frameworks\n\n· System integration experience and skill to integrate application components using Web Services, EJB, REST SOAP and other techniques\n\n· Knowledge in Spring Component, Angular, and Spring Framework such as Spring, Hibernate/JPA, Batch, etc.\n\n· Design, implement, troubleshoot and debug solutions based on Java technology - Java/J2EE, JPA, Spring and related frameworks within a project scope ensuring that work product meets end user acceptance criteria\n\n· Experience developing and integrating applications using services such as APIs/RESTful APIs\n\n· Development experience in Cloud and DevSecOps environments\n\n· Knowledge or experience with Docker, Kubernetes, Git and AWS\n\n· Collaboratively work with functional and technical teams to integrate applications in cloud environment\n\n· Experience working with databases and various data formats and related technologies\n\n· Experience implementing solutions against relational databases and solid SQL querying skills\n\n· Participate in software and architectural development activities\n\n· Be an active participant on an Agile Software team with release and sprint planning, artifact creation, sprint testing, regression testing, demonstrations and retrospectives and solution releases\n\n· Strong problem-solving, analytical, verbal & written communication skills\n\nJob Type: Contract\n\nPay: $70.00 - $75.00 per hour\n\nSchedule:\n• 8 hour shift\n• Day shift\n• Monday to Friday\n\nApplication Question(s):\n• Are you a US citizen?\n• We're looking to fill this position immediately. Are you available to interview with us in a day? Please list dates and times you're available.\n\nEducation:\n• Bachelor's (Preferred)\n\nExperience:\n• DevSecOps: 4 years (Preferred)\n• Java: 5 years (Required)\n• Database: 5 years (Preferred)\n\nWork Location: Remote",
    job_is_remote: false,
    job_posted_at_timestamp: 1683590400,
    job_posted_at_datetime_utc: "2023-05-09T00:00:00.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=developer+jobs&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=developer+jobs&htidocid=Hmv5o-6TBS4AAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: "2023-08-04T00:00:00.000Z",
    job_offer_expiration_timestamp: 1691107200,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: 60,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: null,
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: true,
      degree_preferred: true,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 70,
    job_max_salary: 70,
    job_salary_currency: "USD",
    job_salary_period: "HOUR",
    job_highlights: {
      Qualifications: [
        "We’re looking to hire skilled professionals who will be part of our integral team and will possess extensive Java capability, keen leadership skills and the ability to manage a very congenial but challenging government product owner",
        "IOS mobile app development experience would be a bonus",
        "You will need to be capable of communicating technical ideas to our non-technical stakeholders in a simple and understandable way",
        "Citizenship Status: Must be a US Citizen",
        "Degree: Bachelor’s Degree in Computer Science, Information Technology or related field with coursework in technology-related subjects",
        "Experience: Minimum of 5-7 years of Java Development Experience",
        "Strong working knowledge of Java/J2EE, JPA, Spring, and related frameworks",
        "System integration experience and skill to integrate application components using Web Services, EJB, REST SOAP and other techniques",
        "Knowledge in Spring Component, Angular, and Spring Framework such as Spring, Hibernate/JPA, Batch, etc",
        "Design, implement, troubleshoot and debug solutions based on Java technology - Java/J2EE, JPA, Spring and related frameworks within a project scope ensuring that work product meets end user acceptance criteria",
        "Experience developing and integrating applications using services such as APIs/RESTful APIs",
        "Development experience in Cloud and DevSecOps environments",
        "Knowledge or experience with Docker, Kubernetes, Git and AWS",
        "Collaboratively work with functional and technical teams to integrate applications in cloud environment",
        "Experience working with databases and various data formats and related technologies",
        "Experience implementing solutions against relational databases and solid SQL querying skills",
        "Participate in software and architectural development activities",
        "Be an active participant on an Agile Software team with release and sprint planning, artifact creation, sprint testing, regression testing, demonstrations and retrospectives and solution releases",
        "Strong problem-solving, analytical, verbal & written communication skills",
        "Java: 5 years (Required)",
      ],
      Benefits: ["Pay: $70.00 - $75.00 per hour", "8 hour shift"],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113300",
    job_onet_job_zone: "4",
  },
  {
    employer_name: "Apollose",
    employer_logo:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPd-hps7yHu6ZmQPwa8QzKacpqKLbzwCNNoBVY&s=0",
    employer_website: null,
    employer_company_type: null,
    job_publisher: "OPTnation",
    job_id: "k7BklxsgvYoAAAAAAAAAAA==",
    job_employment_type: "FULLTIME",
    job_title: "Javascript Developer",
    job_apply_link:
      "https://www.optnation.com/javascript-developer-job-in-houston-ms-view-jobid-33721",
    job_apply_is_direct: false,
    job_apply_quality_score: 0.7074,
    job_description:
      "Responsibilities Develop new features or update existing features in JavaScript jQuery HTML/CSS. Work on frontend as well as backend modules based on Node.js and noSQL database. Write automatic unit and functional tests using latest testing technologies. Build software releases and deploy them on our US and Asia Linux servers. Participate to Scrum planning and review meetings. Technology survey and prototyping in collaboration with the technical leader.\n\nKey Skills Proficiency in core JavaScript. Knowledge of front-end development. Experience with popular front-end frameworks and libraries. Knowledge of software development best practices. Problem-solving and critical thinking.",
    job_is_remote: false,
    job_posted_at_timestamp: 1686268800,
    job_posted_at_datetime_utc: "2023-06-09T00:00:00.000Z",
    job_city: null,
    job_state: null,
    job_country: "US",
    job_latitude: 37.09024,
    job_longitude: -95.71289,
    job_benefits: null,
    job_google_link:
      "https://www.google.com/search?gl=us&hl=en&rciv=jb&q=developer+jobs&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=developer+jobs&htidocid=k7BklxsgvYoAAAAAAAAAAA%3D%3D",
    job_offer_expiration_datetime_utc: null,
    job_offer_expiration_timestamp: null,
    job_required_experience: {
      no_experience_required: false,
      required_experience_in_months: null,
      experience_mentioned: true,
      experience_preferred: false,
    },
    job_required_skills: [
      "software development best practices",
      "Problem-solving",
      "critical thinking.",
    ],
    job_required_education: {
      postgraduate_degree: false,
      professional_certification: false,
      high_school: false,
      associates_degree: false,
      bachelors_degree: false,
      degree_mentioned: false,
      degree_preferred: false,
      professional_certification_mentioned: false,
    },
    job_experience_in_place_of_education: false,
    job_min_salary: 25000,
    job_max_salary: 32000,
    job_salary_currency: "USD",
    job_salary_period: "YEAR",
    job_highlights: {
      Qualifications: [
        "Key Skills Proficiency in core JavaScript",
        "Knowledge of front-end development",
        "Experience with popular front-end frameworks and libraries",
        "Knowledge of software development best practices",
        "Problem-solving and critical thinking",
      ],
      Responsibilities: [
        "Work on frontend as well as backend modules based on Node.js and noSQL database",
        "Write automatic unit and functional tests using latest testing technologies",
        "Build software releases and deploy them on our US and Asia Linux servers",
        "Participate to Scrum planning and review meetings",
        "Technology survey and prototyping in collaboration with the technical leader",
      ],
    },
    job_job_title: null,
    job_posting_language: "en",
    job_onet_soc: "15113400",
    job_onet_job_zone: "3",
  },
];
